### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float128' on RaspberryPi

### ISSUE THREAD

**Issue by volkerjaenisch** [colour-science/colour#809] opened 2021-04-29 17:53 UTC
Dear Colour-Science developers!

Many thanks for this cool software. We are using it in scientific probe archiving and are really happy with it.
Our measurement system works on a raspberry PI 4 and Colour-Science is not aware that ARM CPUs does not all have support for the float128 data type.

So importing colour fails with the stacktrace below. 

You have already checked in 

    /home/pi/.local/lib/python3.7/site-packages/colour/io/image.py

for Windows which also does not have this data type:

    if platform.system() not in ('Windows', 'Microsoft'):  # pragma: no cover
        BIT_DEPTH_MAPPING['float128'] = BitDepth_Specification(
            'float128', np.float128, FLOAT, 1, False)

I think this check should be expanded to include RaspberryPi and probably other ARM platforms.

Cheers,
Volker

**BTW : A short and painless hack to get rid of the error is to comment out the lines shown above at the two locations where they occur in image.py.** 

      pi@data:~ $ python3
      Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
      [GCC 8.3.0] on linux
      Type "help", "copyright", "credits" or "license" for more information.
      >>> import colour
      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "/home/pi/.local/lib/python3.7/site-packages/colour/__init__.py", line 97, in <module>
          from .io import (LUT1D, LUT3x1D, LUT3D, LUTSequence, READ_IMAGE_METHODS,
        File "/home/pi/.local/lib/python3.7/site-packages/colour/io/__init__.py", line 7, in <module>
          from .image import ImageAttribute_Specification, convert_bit_depth
        File "/home/pi/.local/lib/python3.7/site-packages/colour/io/image.py", line 99, in <module>
          'float128', np.float128, None, 1, False)
        File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 304, in __getattr__
          "{!r}".format(__name__, attr))
      AttributeError: module 'numpy' has no attribute 'float128'

**Comment by KelSolaar** [comment] 2021-04-30 22:42
Hi @volkerjaenisch,

Yes thanks this is a duplicate of #663 and has been fixed in https://github.com/colour-science/colour/commit/6ea3605eb118c4994b4b53b02ed0f49e1b78cff4.

Cheers,

Thomas

**Closed by KelSolaar** 2021-04-30 22:42 UTC
Labels: API, Critical, Defect, Duplicate
