### ISSUE TITLE
Support OpenImageIO 1.8

### ISSUE THREAD

**Issue by stakemura** [colour-science/colour#357] opened 2017-11-16 17:27 UTC
Currently colour is optionally depended on OpenImageIO 1.5.21 (1 Dec 2015 released).
However colour causes an exception when read_image() is called with OpenImageIO 1.8.x (current version).
It would be very helpful to have the support for OpenImageIO 1.8.x.

**Comment by KelSolaar** [comment] 2017-11-16 18:37
Hi @stakemura,

Yes this is on the radar somehow, @lgritz has actually dropped Boost.Python to Pybind11 in OIIO 1.9.1dev available in [master](https://github.com/OpenImageIO/oiio/tree/master)

Now in regard to what version of OIIO we depend on, I don't think I have ever specified one and I actually did not know 1.8 was breaking so I will look at that.

**Comment by KelSolaar** [comment] 2018-03-10 22:21
@stakemura : I could not reproduce with *OpenImageIO 1.8.9*, I'll close this issue for now, feel free to add more details and I will re-open accordingly.

**Closed by KelSolaar** 2018-03-10 22:21 UTC
Labels: API, Enhancement, P2, Ready
