### ISSUE TITLE
[BUG]: Unable to build the 0.4.0 package using setuptools

### ISSUE THREAD

**Issue by kmilos** [colour-science/colour#945] opened 2022-02-21 17:47 UTC
### Description

Unable to build the 0.4.0 colour package using setuptools (this is for [packaging for the msys2 repo](https://github.com/msys2/MINGW-packages/runs/5277815717?check_suite_focus=true#step:9:907)). Previous 0.3.16 version built fine.

### Code for Reproduction

```python
`python setup.py build`
```

### Exception Message

```shell
`error in colour-science setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`
```

### Environment Information

```shell
MSYS2 (MinGW-w64) Python 3.9.10 w/ setuptools 59.8.0
```

**Comment by kmilos** [comment] 2022-02-21 18:14
Btw, MSYS2 is currently stuck w/ this version of setuptools because of https://www.msys2.org/news/#2021-12-21-potential-incompatibilities-with-newer-python-setuptools

**Comment by KelSolaar** [comment] 2022-02-21 18:32
Hi @kmilos and thanks!

I won't have time to look into that until later today but here are the respective attributes:

[Colour 0.3.16](https://github.com/colour-science/colour/blob/4494cb42ce6c7ee78464c93a4824638e42450a00/setup.py#L129)

```python
extras_require = \
{'development': ['biblib-simple',
                 'coverage',
                 'coveralls',
                 'flake8',
                 'invoke',
                 'jupyter',
                 'mock',
                 'nbformat>=4,<5',
                 'nose',
                 'pre-commit',
                 'pytest',
                 'restructuredtext-lint',
                 'sphinx<=3.1.2',
                 'sphinx_rtd_theme',
                 'sphinxcontrib-bibtex',
                 'toml',
                 'twine',
                 'yapf==0.23'],
 'graphviz': ['pygraphviz'],
 'optional': ['networkx', 'pandas', 'tqdm'],
 'plotting': ['backports.functools_lru_cache', 'matplotlib'],
 'read-the-docs': ['mock',
                   'networkx',
                   'numpy',
                   'pygraphviz',
                   'sphinxcontrib-bibtex']}
```

[Colour 0.4.0](https://github.com/colour-science/colour/blob/07d10da39bdd20f6035db04fc3f989899c8ec17c/setup.py#L141)

```python
extras_require = {
    ':extra == "read-the-docs"': ["numpy>=1.19,<2"],
    "development": [
        "biblib-simple",
        "black",
        "coverage!=6.3",
        "coveralls",
        "flake8",
        "flynt",
        "invoke",
        "jupyter",
        "mypy",
        "pre-commit",
        "pydata-sphinx-theme",
        "pydocstyle",
        "pytest",
        "pytest-cov",
        "pyupgrade",
        "restructuredtext-lint",
        "sphinx>=4,<5",
        "sphinxcontrib-bibtex",
        "toml",
        "twine",
    ],
    "graphviz": ["pygraphviz>=1,<2"],
    "meshing": ["trimesh>=3,<4"],
    "optional": [
        "networkx>=2,<3",
        "pandas>=1,<2",
        "scikit-learn>=1,<2",
        "tqdm>=4,<5",
    ],
    "plotting": ["matplotlib>=3.2,!=3.5.0,!=3.5.1"],
    "read-the-docs": [
        "matplotlib>=3.2,!=3.5.0,!=3.5.1",
        "networkx>=2,<3",
        "pygraphviz>=1,<2",
        "trimesh>=3,<4",
        "pydata-sphinx-theme",
        "sphinxcontrib-bibtex",
    ],
}
```

The `:extra == "read-the-docs"` key is highly suspicious! The `setup.py` file is entirely generated by `Poetry`, we only doctor it to trim the long description and add a header. I suspect that the issue is coming from [Poetry](https://python-poetry.org).

**Comment by KelSolaar** [comment] 2022-02-22 07:58
@kmilos : Would it be hard for you to test whether the removal of `':extra == "read-the-docs"': ["numpy>=1.19,<2"],` is enough for you to get going? I'm happy to release a fix for the time being but I would like to be sure it solves all the problems first.

**Comment by kmilos** [comment] 2022-02-22 08:10
Thanks @KelSolaar, that's exactly it - removing the `':extra == "read-the-docs"': ["numpy>=1.19,<2"],` line seems to let the `python setup.py build` execute as before.

**Comment by KelSolaar** [comment] 2022-02-22 08:14
Thanks for confirming, I will release a new version if not tomorrow, this weekend!

**Comment by kmilos** [comment] 2022-02-22 13:00
@KelSolaar There seems to be an alternative of editing the pyproject.toml as suggested in this [comment](https://github.com/msys2/MINGW-packages/pull/10838#issuecomment-1047725733).

That makes it buildable w/ MSYS2 `python-build` & `python-poetry-core` (there is no full `python-poetry` available) instead of setuptools...

**Comment by KelSolaar** [comment] 2022-02-22 23:17
I can certainly also change the build backend, it does not solve the fact that the produced `setup.py` file is seemingly incorrect though?

**Comment by kmilos** [comment] 2022-02-23 09:02
Indeed.

FYI, I have also tried w/ newer setuptools 60.9.3 in a conda environment, and it throws the exact same error.

**Comment by KelSolaar** [comment] 2022-02-25 21:36
I will close this one as I addressed the issue pointed out by @finswimmer in our `pyproject.toml` file and release 0.4.1.

**Closed by KelSolaar** 2022-02-25 21:36 UTC
Labels: Defect, Major, Distribution

**Comment by kmilos** [comment] 2022-02-25 21:38
Thanks!
