### ISSUE TITLE
How to perform colour correction with a "ColorChecker" reference image?

### ISSUE THREAD

**Issue by bsdis** [colour-science/colour#598] opened 2020-06-08 18:16 UTC
Hi, 
I have images of a colorchecker and I would like to perform color calibration of these images.
As I understand I have to do extract the 24 colour squares of the colorchecker, Convert from sRGB to RGB by applying inverse gamma, convert RGB to XYZ using 3x3 matrix, convert XYZ to Lab using standard formula and D6500 white point - perform a regression to find conversion coefficients - and then convert all pixels using the coefficients and the finally transform the converted image back into sRGB space.
Is that correctly understood, and is that possible to do using this library? (all the color conversions - not the extractions from images etc)
If yes - are there any examples available?

thanks

**Comment by KelSolaar** [comment] 2020-06-09 05:34
Hi @bsdis,

It is absolutely possible and I do that quite regularly.

Assuming you have the data for the colour rendition chart, at the basic minimum, this is what you need to do: https://github.com/colour-science/colour/blob/c3245b1830323991823f20580f81eee856dcc04c/colour/characterisation/correction.py#L852

We have a [repository](https://github.com/colour-science/colour-checker-detection) which does extraction and provides an example of colour correction here: https://github.com/colour-science/colour-checker-detection/blob/develop/colour_checker_detection/examples/examples_detection.ipynb

**Comment by bsdis** [comment] 2020-06-09 08:00
Ahh ok. Really nice :)
I hope its ok to ask some follow up questions:
1) In the notebook you preprocess your images with `dcraw -T -g 2.4 12.92 *.CR2`. This basically encodes images as sRGB png images right?
2) I ran your example on 4 test images i had of the same scene where i have changed the lighting in each scene.
I get this result which is pretty nice actually
<img width="772" alt="Screenshot 2020-06-09 at 09 57 07" src="https://user-images.githubusercontent.com/1256202/84121632-b5e79e00-aa37-11ea-8e87-e18b9edb61ee.png">

But it seems that especially if you look on the white background its still not the same on the "after calibration" images. Is this to be expected? Can that be fixed somehow?

**Comment by bsdis** [comment] 2020-06-09 08:25
Here is actually a better image. I have multiplied with and capped at 255, which also shows that some channels are saturated after the calibration.

<img width="621" alt="Screenshot 2020-06-09 at 10 23 00" src="https://user-images.githubusercontent.com/1256202/84124276-4a9fcb00-aa3b-11ea-9db7-0e7c05caab97.png">

Is this because i need to do a white balancing also?

**Comment by KelSolaar** [comment] 2020-06-09 09:44
Hi @bsdis,

This is a great example of why relying on a colour rendition chart for colour correction is not the solution to all the imaging calibration problems as `$COLOUR_RENDITION_CHART_MAKER` claims it is.

What is happening here is that your scene illumination is changing while the ColorChecker Classic values are given for a particular illuminant, i.e. CIE D50. Ideally for things to really work, your scene should be lit with CIE D50 so that you can perform colour correction against the published values.

Ideally, you would need to measure the spectral irradiance of the scene and the spectral reflectance of the ColorChecker Classic (with a spectro-photometer) and recompute its values for the particular scene.

Alternatively, something cheap is to neutralise on the bottom row after the colour correction but it is obviously not ideal!

I hope that makes sense!

**Comment by bsdis** [comment] 2020-06-09 10:25
Hi @KelSolaar 

Aha - yes that makes perfect sense. I have to keep that in mind.
If I first wanted to try the cheap method, you say "neutralise on the bottom row after the colour correction". How exactly is that done? In your code, the final image is generated by doing:
```
    im = colour.cctf_encoding(
        colour.colour_correction(
            COLOUR_CHECKER_IMAGES[i], swatches, REFERENCE_SWATCHES))
```
So I guess `im` is in sRGB colorspace? Would i do the neutralise directly on this image, or would I convert it to another colorspace first?
Also - would you cut a square from each of the bottom patches to neutralize after, and how would you do it?

Sorry - I hope its not to many questions.

Thanks :)

**Comment by KelSolaar** [comment] 2020-06-09 11:07
Yeah, so you would need to neutralise before that conversion, colour correction, white-balancing  and, most of the operations must ideally be done on floating-point linear data. The idea is to compute the average RGB colour of one of the swatches of the bottom row, we commonly take the third from the bottom right in the VFX industry, divide your image by it so that this swatch is white (or close to it because you only took the average) and then multiply the image by the value of that swatch, it should be around [0.19~, 0.19~, 0.19~] for sRGB.

**Comment by bsdis** [comment] 2020-06-09 13:07
Hi @KelSolaar 

Hmm I think I might have misunderstood you.
I understood it like adding these 2 lines:
```
    im_ = COLOUR_CHECKER_IMAGES[i]/colour_checker.data['neutral 5 (.70 D)']
    im *= im_
```
So code becomes like this
```
for i, swatches in enumerate(SWATCHES):
    swatches_xyY = colour.XYZ_to_xyY(colour.RGB_to_XYZ(
        swatches, D65, D65, colour.RGB_COLOURSPACES['sRGB'].RGB_to_XYZ_matrix))

    colour_checker = colour.characterisation.ColourChecker(
        os.path.basename(COLOUR_CHECKER_IMAGE_PATHS[i]),
        OrderedDict(zip(REFERENCE_COLOUR_CHECKER.data.keys(), swatches_xyY)),
        D65)
    
    plot_multi_colour_checkers(
        [REFERENCE_COLOUR_CHECKER, colour_checker])
    
    swatches_f = colour.colour_correction(swatches, swatches, REFERENCE_SWATCHES)
    swatches_f_xyY = colour.XYZ_to_xyY(colour.RGB_to_XYZ(
        swatches_f, D65, D65, colour.RGB_COLOURSPACES['sRGB'].RGB_to_XYZ_matrix))
    colour_checker = colour.characterisation.ColourChecker(
        '{0} - CC'.format(os.path.basename(COLOUR_CHECKER_IMAGE_PATHS[i])),
        OrderedDict(zip(REFERENCE_COLOUR_CHECKER.data.keys(), swatches_f_xyY)),
        D65)
    
    plot_multi_colour_checkers(
        [REFERENCE_COLOUR_CHECKER, colour_checker])
    
    ##### ADDED WHITE BALANCING HERE:
    im_ = COLOUR_CHECKER_IMAGES[i]/colour_checker.data['neutral 5 (.70 D)'] # divide using broadcasting
    im *= im_
    ##########################
    im = colour.cctf_encoding(
        colour.colour_correction(
            im, swatches, REFERENCE_SWATCHES))
    b4after.append( [COLOUR_CHECKER_IMAGES[i],im] )
    plot_image(im);
```

But this gives me quite strange results. 
What did i misunderstand here?

**Comment by KelSolaar** [comment] 2020-06-09 20:08
You would need to divide by the average value of the colour checker in the image, i.e. `COLOUR_CHECKER_IMAGES[I]` and multiply by that of the reference one colour_checker.data['neutral 5 (.70 D)']

**Comment by bsdis** [comment] 2020-06-09 21:18
As I understand the code, the following variables are:

```COLOUR_CHECKER_IMAGES[i] <--- Sample image```

```colour_checker.data['neutral 5 (.70 D)']) <--- average value of neutral 5 swatch of sample image```

```REFERENCE_COLOUR_CHECKER.data['neutral 5 (.70 D)'] <--- reference value of colorchecker for neutral 5```

So: divide by the average value of the colour checker in the image, i.e. COLOUR_CHECKER_IMAGES[I] and multiply by that of the reference one 
would be:
```
im = (COLOUR_CHECKER_IMAGES[i]/colour_checker.data['neutral 5 (.70 D)'])*\
        REFERENCE_COLOUR_CHECKER.data['neutral 5 (.70 D)']
```
Is that correct?

However it still gives quite different backgrounds though. 

<img width="264" alt="Screenshot 2020-06-09 at 22 38 34" src="https://user-images.githubusercontent.com/1256202/84200329-d995fd00-aaa6-11ea-9a84-12720c2c03d2.png">

So I guess thats due to my scene illumination changing while the ColorChecker Classic values are given for a particular illuminant like you mentioned, right?

What I actually wanted to achieve was to be able to take an arbitrary image under an arbitrary illumination and and arbitrary camera, and somehow calibrate those into same colorspace, so that I could directly compare the colors in the in images. In each picture there would always be a colorchecker of course. 
So I guess thats actually impossible then?

**Comment by KelSolaar** [comment] 2020-06-10 10:41
> Is that correct?

Not really, you would need to divide each given image by its own colour checker Neutral 5 swatch average, because each image has its own illuminant, you need to neutralise for each one of them accordingly and individually.

> So I guess thats due to my scene illumination changing while the ColorChecker Classic values are given for a particular illuminant like you mentioned, right?

Assuming you have neutralised each one of them, you will see that not only their whites are closer, but also that their exposure is roughly the same! You will still have discrepancies though because of the illuminant differences.

**Comment by bsdis** [comment] 2020-06-21 18:26
Hi @KelSolaar 
Hope its okay i keep this thread running.
In your notebook (https://github.com/colour-science/colour-checker-detection/blob/develop/colour_checker_detection/examples/examples_detection.ipynb) 
you do:
```
    plot_image(colour.cctf_encoding(
        colour.colour_correction(
            COLOUR_CHECKER_IMAGES[i], swatches, REFERENCE_SWATCHES)));
```

the output of colour.cctf_encoding seem to be in the range -0.52 1.47. Should that not be in the range 0 and 1?

**Comment by KelSolaar** [comment] 2020-06-21 21:01
Hi,

> Hope its okay i keep this thread running.

Absolutely and good question! We never (pretty much never) clip data in Colour because this is what allows inversion of the transforms. Yes, you will often get negative values and values over one, this is by design. Whether it makes sense is something we are expecting the user to assess and is dependent on the usage. For your current case, because you are plotting an image, it would make sense to clip the values. They are effectively being clipped by `plot_image` just before being sent to `plt.imshow` because Matplotlib will raise an exception otherwise.

**Comment by bsdis** [comment] 2020-06-21 21:15
I see. Instead of clipping, wouldn't it make more sense to keep the information as much as possible by shifting to min=0 and divide with max value to get 0<=x<=1 ?

**Comment by KelSolaar** [comment] 2020-06-21 21:22
Good question again!

We cannot really decide for the user here, given we are often working with negative out-of-gamut colours or very large HDR values, e.g. [1.e7, 1e9], the image would be entirely black except for a small speckle, i.e. the Sun, in a lot of cases.

A single large value is needed to throw you off trajectory here and it happens all the time in the type of applications we use Colour for. We really do swim in an ocean of **nans** and **infs** :)

**Comment by bsdis** [comment] 2020-06-21 21:37
haha yes ok. thats a really good point :D

**Comment by KelSolaar** [comment] 2020-06-21 21:51
depending on the number of terms/degree you use, you will get the same results, basically, all the methods are equivalent for degree 1 (linear).

**Comment by bsdis** [comment] 2020-06-21 22:19
@KelSolaar I was hoping I could maybe get your opinion on the path I have chosen so far.

My usecase is that I need to compare colors in different images across many images. 

The challenge here is that I have no idea about the lighting used on each image and I have no idea about the camera used for each image (could be some phone cam or some DSLR cam or whatever). The only thing I know is that an xrite colorchecker is present on each image taken. Input images are in sRGB jpeg which is default output from many devices.. 
As Initially stated i need to be able to compare colors across all images, which means i need to transform all images into same colorspace-coordinate system so to say. I know that it will be impossible to perfectly normalize the colors as long as i have no control of the lightsource and the device, but I am looking to do it as good as possible. For future images i can change the xrite colorchecker with something more appropriate if need be. Is the `color-correction` course the right way to go for a problem like that?

**Comment by KelSolaar** [comment] 2020-06-21 22:53
I would maybe try to see if you can infer the illuminant from the scene, there is a great deal of literature on the topic, e.g. https://www.groundai.com/project/rehabilitating-the-color-checker-dataset-for-illuminant-estimation/. I never tried any of that unfortunately but it is certainly on my radar when time permits!

Otherwise, your approach is certainly correct!

**Comment by KelSolaar** [comment] 2020-06-21 22:55
This publication is of particular interest: https://arxiv.org/abs/1504.04548

**Comment by bsdis** [comment] 2020-06-22 10:19
AHa...that sounds really interesting... I will look into that. Thanks a lot for the pointers! Will be sure to feed back what I find out :)

**Comment by KelSolaar** [comment] 2020-10-11 07:05
Closing this one for now! Feel free to add comments and I will re-open!

**Closed by KelSolaar** 2020-10-11 07:05 UTC
Labels: API, Discussion
