### ISSUE TITLE
"colour.SpectralShape" class converts int to float.

### ISSUE THREAD

**Issue by Chandler** [colour-science/colour#324] opened 2017-05-16 23:52 UTC
```
(Pdb) shape = SpectralShape(int(2),int(10),int(2))
(Pdb) shape.interval
2.0
```

This breaks inside of `multi_spd_plot` which uses spectral shapes to index into numpy arrays, which isn't possible with floats.

```
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    plot.multi_spd_plot(spds, use_spds_colours=True)
  File "/Users/chandler/miniconda2/envs/py6s-env/lib/python2.7/site-packages/colour/plotting/colorimetry.py", line 215, in multi_spd_plot
    XYZ = spectral_to_XYZ(spd, cmfs, illuminant) / 100
  File "/Users/chandler/miniconda2/envs/py6s-env/lib/python2.7/site-packages/colour/colorimetry/tristimulus.py", line 813, in spectral_to_XYZ
    return function(spd, cmfs, illuminant, **kwargs)
  File "/Users/chandler/miniconda2/envs/py6s-env/lib/python2.7/site-packages/colour/colorimetry/tristimulus.py", line 698, in spectral_to_XYZ_ASTME30815
    XYZ = method(spd, cmfs, illuminant)
  File "/Users/chandler/miniconda2/envs/py6s-env/lib/python2.7/site-packages/colour/colorimetry/tristimulus.py", line 555, in spectral_to_XYZ_tristimulus_weighting_factors_ASTME30815
    int(cmfs.shape.start), int(cmfs.shape.end), int(spd.shape.interval)))
  File "/Users/chandler/miniconda2/envs/py6s-env/lib/python2.7/site-packages/colour/colorimetry/tristimulus.py", line 267, in tristimulus_weighting_factors_ASTME202211
    W = S[::shape.interval, np.newaxis] * Y[::shape.interval, :]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by KelSolaar** [comment] 2017-05-18 06:46
@Chandler : I have never run against that issue, quite interesting. Do you have similar traceback with that example file: https://github.com/colour-science/colour/blob/develop/colour/examples/plotting/examples_colorimetry_plots.py

It is using the `multi_spd_plot` plot definition multiple times.

**Comment by KelSolaar** [comment] 2017-06-09 09:41
@Chandler : Any news from this one? I'll close the ticket in a few days if not. Cheers!

**Comment by KelSolaar** [comment] 2017-06-17 05:46
I cannot reproduce the issue, closing for now, feel free to comment back @Chandler and I will re-open it as needed.

**Closed by KelSolaar** 2017-06-17 05:46 UTC
Labels: API, Defect, Normal, Ready

**Comment by KelSolaar** [comment] 2017-06-19 10:46
@Chandler : I just successfully reproduced your issue, its seems to have been introduced by latest Numpy version.

**Comment by Chandler** [comment] 2017-06-19 17:41
oh awesome! sorry I didn't have time to dig further
