### ISSUE TITLE
"colour.write_image" definition does not work with "OpenImageIO 2.x".

### ISSUE THREAD

**Issue by thunders82** [colour-science/colour#516] opened 2019-10-03 14:38 UTC
Hi,

This issue is probably not directly related to 'colour' but you may be able to give me a hand ?
I'm trying to write an image to disk but it seems I'm missing something... : 

> Traceback (most recent call last):
>   File "examples_detection.py", line 153, in <module>
>     colour.io.write_image(final_image, path)
>   File "/usr/local/lib/python2.7/dist-packages/colour/io/image.py", line 188, in write_image
>     from OpenImageIO import ImageOutput, ImageOutputOpenMode, ImageSpec
> **ImportError: cannot import name ImageOutputOpenMode**

I've re-installed OpenImageIO with one of latest version but doesn't change much. Here is my environment : 

> Interpreter :                                                             
>        python : 2.7.15+ (default, Jul  9 2019, 16:51:35)                     
>                 [GCC 7.4.0]                                                  
>                                                                              
>    colour-science.org :                                                      
>        colour : 0.3.13                                                       
>        colour-checker-detection : 0.1.0                                      
>                                                                              
>    Runtime :                                                                 
>        numpy : 1.16.5                                                        
>        scipy : 1.2.2                                                         
>        matplotlib : 2.2.4                                                    
>        OpenImageIO : 2.1.4dev                                                
>        opencv : 3.4.5                                                        

I hope you be able to help.

Thank you,

Geoffrey

**Comment by KelSolaar** [comment] 2019-10-03 18:34
Hi @thunders82 / Geoffrey,

This is fixed in [develop](https://github.com/colour-science/colour/tree/develop), note that a few things happened as per the current [pre-release notes](https://gist.github.com/KelSolaar/4a6ebe9ec3d389f0934b154fec8df51d):

- [Imageio](https://github.com/imageio/imageio) is now a requirement! It can be installed with `pip install imageio` and will come by default when you install **Colour** in the future. If you need to write OpenEXR files just issue `python -c "import imageio;imageio.plugins.freeimage.download()"`.
- [OpenImageIO](https://github.com/OpenImageIO/oiio) is now supported for both 1 and 2 major versions, so your error should go away.

For practical purposes, you should not need **OpenImageIO** only **Imageio** which is available on all platforms and less challenging than the former to get running. The functionality is pretty much the same too.

Cheers,

Thomas

**Comment by thunders82** [comment] 2019-10-03 19:06
Thanks a lot Thomas. 
I'll try it as soon as I can.

**Comment by KelSolaar** [comment] 2019-10-03 19:23
Sweet! Let me know how it goes then :)

**Comment by thunders82** [comment] 2019-10-03 19:23
@KelSolaar / Thomas ,
Just had a quick go but after install :

> git clone git://github.com/colour-science/colour.git -b develop
> cd colour
> pip install .

I've got this issue when I load the script that was working before : 

>   File "/usr/local/lib/python2.7/dist-packages/colour/utilities/deprecation.py", line 239, in __getattr__
>     usage_warning(str(change))
>   File "/usr/local/lib/python2.7/dist-packages/colour/utilities/verbose.py", line 277, in usage_warning
>     warning(*args, **kwargs)
> /usr/local/lib/python2.7/dist-packages/colour/utilities/verbose.py:221: ColourUsageWarning: "colour.models.XYZ_to_colourspace_model" object is deprecated and will be removed in a future release.
>   warn(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/colour/utilities/deprecation.py", line 239, in __getattr__
>     usage_warning(str(change))
>   File "/usr/local/lib/python2.7/dist-packages/colour/utilities/verbose.py", line 277, in usage_warning
>     warning(*args, **kwargs)
> /usr/local/lib/python2.7/dist-packages/colour/utilities/verbose.py:221: ColourUsageWarning: "colour.models.oetf_sRGB" object has been renamed to "colour.models.eotf_inverse_sRGB".
>   warn(*args, **kwargs)
> Traceback (most recent call last):
>   File "examples_detection.py", line 26, in <module>
>     from colour_checker_detection import (
>   File "/usr/local/lib/python2.7/dist-packages/colour_checker_detection/__init__.py", line 22, in <module>
>     from .detection import (colour_checkers_coordinates_segmentation,
>   File "/usr/local/lib/python2.7/dist-packages/colour_checker_detection/detection/__init__.py", line 5, in <module>
>     from .segmentation import (colour_checkers_coordinates_segmentation,
>   File "/usr/local/lib/python2.7/dist-packages/colour_checker_detection/detection/segmentation.py", line 25, in <module>
>     from colour.models import oetf_sRGB, oetf_reverse_sRGB
> ImportError: cannot import name oetf_reverse_sRGB

The install is still called 0.3.13 maybe I did something wrong ?

Thank you,

Geoffrey

**Comment by KelSolaar** [comment] 2019-10-03 19:30
Ah right! So those are API changes that are not yet in the distributed version of `colour-checker-detection`, however, if you grab the [v0.1.1](https://github.com/colour-science/colour-checker-detection/tree/feature/v0.1.1) branch, it should be fixed too!

It is not merged yet in develop because the unit tests are breaking on Linux, so I need to take a look tonight.

Overall, the problem is that I need to release **Colour** first AND then release the other dependant packages, this should hopefully happen in the coming 2 weeks!

**Comment by thunders82** [comment] 2019-10-03 19:36
Alright that's fine. I'll wait to 2 additional weeks to avoid to be lost with all the releases.
Let me know when ready and I'll give it go.
Thanks again for your help.

**Comment by KelSolaar** [comment] 2019-10-03 19:37
Sounds good! If you are not in a hurry, it is surely the simpler path :)

**Comment by hayzem** [comment] 2019-10-12 15:10
I was getting the same error as @thunders82 mentioned. Then read the comments and pulled `color@develop` then installed `imageio` via pip. Since `OpenImageIO` was installed in the path I removed it and updated my code(added `method` and removed `attributes`).

> ...
> For practical purposes, you should not need **OpenImageIO** only **Imageio** which is available on all platforms and less challenging than the former to get running. The functionality is pretty much the same too.
> ...

I was so happy to hear this since setting up `OpenImageIO` with multiple python environments was quite time consuming. 

Then I realized that I am not able to get image attributes if I use `method='imageio'` as I started to refactor the code 🙄 Seems like I need to switch back to `OpenImageIO` method. 

I also realized that even with `imageio` it is possible to get image attributes. That would be nice to add it though. I would like to send a PR, if I could get that working.

ps: I have been only recently started to using `colour`. I am so surprised and thankful to see the great work put in `color-science`.

**Comment by KelSolaar** [comment] 2019-10-12 22:33
Hi @hayzem,

I must admit that I haven't look at how attributes work yet with **Imageio**, my naive assumption was that it would not be that much of a used feature anyway, proven wrong :) I was also thinking that it would be radically different from **OpenImageIO** that it would be incompatible anyway.

Happy to take a PR and discuss about it.

**Comment by KelSolaar** [comment] 2019-10-14 07:16
Quickly looking at it, the first step would be to not lose the `meta` attribute:

```python
>>> colour.read_image('colour/examples/plotting/resources/Ishihara_Colour_Blindness_Test_Plate_3.png').meta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'meta'
>>> imageio.imread('colour/examples/plotting/resources/Ishihara_Colour_Blindness_Test_Plate_3.png').meta
Dict([('srgb', 0), ('XML:com.adobe.xmp', '<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:tiff="http://ns.adobe.com/tiff/1.0/">\n         <tiff:Orientation>1</tiff:Orientation>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n')])
```

**Comment by KelSolaar** [comment] 2019-10-20 19:33
@thunders82 : I was hoping to be able to release 0.3.14 over the weekend but there has been a regression on RtD which currently prevents the documentation to build: https://github.com/readthedocs/readthedocs.org/issues/6308

I will keep you posted!

**Comment by thunders82** [comment] 2019-10-22 08:57
No worries! Thanks for letting me know. I'll wait for your green flag

**Comment by KelSolaar** [comment] 2019-10-22 08:58
The RtD team fixed the issue, crossing fingers for this weekend! :)

**Comment by thunders82** [comment] 2019-10-22 09:17
Good news and fingers crossed!

**Comment by KelSolaar** [comment] 2019-10-26 05:24
Closing this one as I will release in the coming hours!

**Closed by KelSolaar** 2019-10-26 05:24 UTC
Labels: API, Defect, Major
