### ISSUE TITLE
How to calculate the volume of 1000nits DCI-P3 colorspace?

### ISSUE THREAD

**Issue by Wangld5** [colour-science/colour#1009] opened 2022-07-08 02:45 UTC
### Question

Hi, I want to know how to set the value of luminance of the colorspace and calculate the volume of it. For example, how to calculate the volume of DCI-P3 colorspace when the luminance is 1000nit. Thank you.

**Comment by KelSolaar** [comment] 2022-08-25 06:55
Closing as duplicate of https://github.com/colour-science/colour/discussions/1010

**Closed by KelSolaar** 2022-08-25 06:55 UTC
Labels: Discussion
